### ISSUE TITLE
manifest-styles.json not created on npm start

### ISSUE THREAD

**Issue by kalvinwang** [cagov/benefits-screener#27]
We expecte manifest-styles.json to be have been created during npm start but it's not, so the app crashes

To replicate: clone the repo, run npm install and then npm start
Node version: tested with both v12.11.1 and 12.16.2

```Error: Cannot find module '../data/manifest-styles.json'
Require stack:
- /Users/kalvin/Sites/benefits-screener/src/routes/single-page-app.js
- /Users/kalvin/Sites/benefits-screener/src/routes/index.js
- /Users/kalvin/Sites/benefits-screener/src/app.js
- /Users/kalvin/Sites/benefits-screener/src/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:780:15)
    at Function.Module._load (internal/modules/cjs/loader.js:685:27)
    at Module.require (internal/modules/cjs/loader.js:838:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/kalvin/Sites/benefits-screener/src/routes/single-page-app.js:8:24)
    at Module._compile (internal/modules/cjs/loader.js:945:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
    at Module.load (internal/modules/cjs/loader.js:798:32)
    at Function.Module._load (internal/modules/cjs/loader.js:711:12)
    at Module.require (internal/modules/cjs/loader.js:838:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/kalvin/Sites/benefits-screener/src/routes/single-page-app.js',
    '/Users/kalvin/Sites/benefits-screener/src/routes/index.js',
    '/Users/kalvin/Sites/benefits-screener/src/app.js',
    '/Users/kalvin/Sites/benefits-screener/src/index.js'
  ]
}
[nodemon] app crashed - waiting for file changes before starting...```

**Comment by kalvinwang** [comment]
Fixed by @sharonwarner in https://github.com/cagov/benefits-screener/pull/28
